name: Build Client

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build client
      working-directory: ./Vatsim.Vatis
      run: |
        dotnet publish --runtime win-x64 --self-contained true --configuration Release --framework net6.0-windows `
        -p:PublishReadyToRun=true --output ./publish

    - name: Client Hash
      run: |
        $hash = (Get-FileHash .\Vatsim.Vatis\publish\vATIS.exe -Algorithm SHA256).Hash.ToLower()
        echo "CLIENT_HASH=$hash" >> $env:GITHUB_ENV

    - name: Checkout VatsimAuth
      uses: actions/checkout@v3
      with:
        repository: vatis-project/auth
        path: auth
        token: ${{ secrets.GH_TOKEN }}

    - name: VatsimAuth CMake
      working-directory: auth
      run: |
        cmake -E make_directory build
        cd build
        cmake .. -DCLIENT_HASH=${{ env.CLIENT_HASH }} -DVATSIM_CLIENT_ID=${{ secrets.CLIENT_ID }} -DVATSIM_CLIENT_KEY=${{ secrets.CLIENT_KEY }}
        cmake --build . --config RelWithDebInfo

    - name: Copy Client Files
      run: |
        Copy-Item -Path .\auth\build\RelWithDebInfo\VatsimAuth.dll -Destination .\Vatsim.Vatis\publish\

    - name: Get Client Version
      run: |
        $path = ls .\Vatsim.Vatis\publish\vATIS.dll | select -First 1 | % fullname
        $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($path).ProductVersion
        echo "CLIENT_VER=$version" >> $env:GITHUB_ENV
        "!define Version ""$version""" | Out-File -FilePath .\Installer\Version.txt

    - name: Create Installer
      uses: joncloud/makensis-action@v4
      with:
        script-file: '.\Installer\installer.nsi'

    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: vATIS-Setup-${{ env.CLIENT_VER }}
        path: .\Installer\vATIS-Setup-${{ env.CLIENT_VER }}.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: vATIS ${{ env.CLIENT_VER }}
        prerelease: true
        draft: true
        files: vATIS-Setup-${{ env.CLIENT_VER }}.exe
